name: Scrape SSB population (daily)

on:
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run-pop-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci || npm i

      - name: Scrape SSB population (daily-only)
        run: npm run scrape:pop

      - name: Commit & push changes (if any)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/pop_daily.json
            git commit -m "chore: population daily snapshot [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
